version: 2.1
commands:
  test:
    steps:
      - checkout
      - run:
          name: Initial Setup
          command: |
            python --version
            python3 --version
            curl https://bootstrap.pypa.io/get-pip.py | python
            pip --version
            git config --global user.email "bot@renovateapp.com"
            git config --global user.name "Renovate Bot"
            git --version

      - restore_cache:
        keys:
          - dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - dependency-cache-{{ .Branch }}-
          - dependency-cache-

      - restore_cache:
        keys:
          - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - yarn-packages-v1-{{ .Branch }}-
          - yarn-packages-v1-

      - run:
          name: Installing Dependencies
          command: |
            yarn install --frozen-lockfile
            pip install --user -r requirements.txt

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - '.cache'
            - '.eslintcache'

      - save_cache:
        paths:
          - ~/.cache/yarn
        key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Lint
          command: |
            yarn eslint --format junit -o test-results/lint/results.xml
            yarn prettier
            yarn test-schema
            yarn type-check

      - run:
          name: Build
          command: |
            yarn build

      - run:
          name: Unit Tests
          command: |
            yarn jest --maxWorkers=2  --ci --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: 'test-results/jest'
            JEST_JUNIT_OUTPUT_NAME: 'results.xml'

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

      - run:
          name: E2E Tests
          command: |
            yarn test-e2e

      - run:
          name: Coverage
          command: |
            bash <(curl -s https://codecov.io/bash) -Z -C $CIRCLE_SHA1
          when: always
jobs:
  test_node_10:
    docker:
      - image: amd64/node:10.18.0@sha256:15a23eefad1798c98238fe71b22b65e20c26c17f139505cf6abcab53a740554a
    steps:
      - test
  release:
    docker:
      - image: amd64/node:10.18.0@sha256:15a23eefad1798c98238fe71b22b65e20c26c17f139505cf6abcab53a740554a
    steps:
      - checkout
      - restore_cache:
        keys:
          - dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - dependency-cache-{{ .Branch }}-
          - dependency-cache-
      - restore_cache:
        keys:
          - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - yarn-packages-v1-{{ .Branch }}-
          - yarn-packages-v1-
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn semantic-release
      - run: curl -X POST -d '{}' $NETLIFY_DEPLOY_WEBHOOK

workflows:
  version: 2
  test_and_release:
    jobs:
      - test_node_10
      - release:
          requires:
            - test_node_10
          filters:
            branches:
              only:
                - master
